### ISSUE TITLE
GitHub security alert

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-SRX/NSLS-II-SRX.github.io#1]
![image](https://user-images.githubusercontent.com/13209176/118666654-59e9d580-b7c1-11eb-9fcf-3e812d6d0811.png)

**Comment by mrakitin** [comment]
@gwbischof, @dmgav, could you please take care of this vulnerability issue? I keep getting weekly reminders via GitHub notifications.

**Comment by andrewmkiss** [comment]
@mrakitin @gwbischof @dmgav While this is in github, it's not really code. I think this is in the sphinx part, which is hopefully just making html files. Maybe the javascript is used in the html, but at least on my linux mint machine, I can only get 1.9, not the 1.12 that GH wants

**Comment by mrakitin** [comment]
It complains about https://github.com/NSLS-II-SRX/NSLS-II-SRX.github.io/blob/master/docs/_static/underscore.js. I believe the latest sphinx can get a more up-to-date file.

**Comment by andrewmkiss** [comment]
I do not see a newer version of libjs-underscore in apt on ubuntu 20.04. The latest version is 1.9-1 which makes a reference to that security issue. Sphinx and underscore are up-to-date (through apt) on my system. The only other thing I could consider is cloning from git and using that...but that is sort of a hassle and it obviously won't be maintained by apt (i'll have to do it manually)

**Comment by mrakitin** [comment]
@andrewmkiss, check #2, where I pushed the auto-generated files by the newest sphinx version. That installed `underscore.js` v1.12.

**Comment by andrewmkiss** [comment]
Ah! I see. I hadn't considered installing sphinx through conda. I'll merge your pull request and switch over to using conda instead of the apt repos.

**Comment by mrakitin** [comment]
Thanks, @andrewmkiss!
